# Every function's output against inst/conformance/fixture.nt must exactly
# match its golden CSV. This is the parity contract a future Python port is
# built against (inst/conformance/README.md documents the exact format).
# Goldens are regenerated by scripts/040-build-goldens.R, never hand-edited.

conformance_dir <- system.file("conformance", package = "cybedtools")
if (!nzchar(conformance_dir)) {
  # Running against the source tree rather than an installed package
  # (devtools::load_all()); fall back to the checkout path.
  conformance_dir <- testthat::test_path("..", "..", "inst", "conformance")
}

skip_if_no_conformance_fixture <- function() {
  skip_if_not_installed("rdflib")
  skip_if_not(
    file.exists(file.path(conformance_dir, "fixture.nt")),
    "conformance fixture not found; run scripts/040-build-goldens.R"
  )
}

read_golden <- function(name) {
  readr::read_csv(
    file.path(conformance_dir, "goldens", paste0(name, ".csv")),
    col_types = readr::cols(.default = "c"),
    na = ""
  )
}

as_char_frame <- function(df) {
  df <- as.data.frame(lapply(df, as.character), stringsAsFactors = FALSE)
  df[is.na(df)] <- ""
  df
}

test_that("framework_metadata matches its golden", {
  skip_if_no_conformance_fixture()
  rdf <- rdflib::rdf_parse(file.path(conformance_dir, "fixture.nt"), format = "ntriples")

  result <- framework_metadata(rdf) |> dplyr::arrange(.data$framework)
  golden <- read_golden("framework_metadata")

  expect_equal(as_char_frame(result), as_char_frame(golden))
})

test_that("unit_element_bindings matches its golden", {
  skip_if_no_conformance_fixture()
  rdf <- rdflib::rdf_parse(file.path(conformance_dir, "fixture.nt"), format = "ntriples")

  result <- unit_element_bindings(rdf) |> dplyr::arrange(.data$role, .data$element)
  golden <- read_golden("unit_element_bindings")

  expect_equal(as_char_frame(result), as_char_frame(golden))
})

test_that("unit_relation_bindings matches its golden", {
  skip_if_no_conformance_fixture()
  rdf <- rdflib::rdf_parse(file.path(conformance_dir, "fixture.nt"), format = "ntriples")

  result <- unit_relation_bindings(rdf) |>
    dplyr::arrange(.data$from_unit, .data$to_unit, .data$relation)
  golden <- read_golden("unit_relation_bindings")

  expect_equal(as_char_frame(result), as_char_frame(golden))
})

test_that("framework_similarity matches its golden", {
  skip_if_no_conformance_fixture()
  rdf <- rdflib::rdf_parse(file.path(conformance_dir, "fixture.nt"), format = "ntriples")

  result <- framework_similarity(rdf, from = "fixture-wf1", to = "fixture-wf2", n = 5) |>
    dplyr::mutate(score = round(.data$score, 10)) |>
    dplyr::arrange(.data$from_unit, .data$rank)
  golden <- read_golden("framework_similarity") |>
    dplyr::mutate(rank = as.integer(.data$rank))

  expect_equal(nrow(result), nrow(golden))
  expect_equal(as.character(result$from_unit), golden$from_unit)
  expect_equal(as.character(result$to_unit),   golden$to_unit)
  expect_equal(as.numeric(result$score), as.numeric(golden$score), tolerance = 1e-9)
  expect_equal(as.character(result$strength), golden$strength)
  expect_equal(result$rank, golden$rank)
})

test_that("cybed_license matches its golden", {
  skip_if_no_conformance_fixture()

  result <- cybed_license() |> dplyr::arrange(.data$slug)
  golden <- read_golden("cybed_license")

  expect_equal(as_char_frame(result), as_char_frame(golden))
})

test_that("framework_summary matches its golden", {
  skip_if_no_conformance_fixture()

  result <- cybedtools::framework_summary |> dplyr::arrange(.data$framework_slug)
  golden <- read_golden("framework_summary")

  expect_equal(as_char_frame(result), as_char_frame(golden))
})

test_that("golden CSVs use LF line endings and no literal NA", {
  skip_if_no_conformance_fixture()

  for (name in c("framework_metadata", "unit_element_bindings",
                  "unit_relation_bindings", "framework_similarity",
                  "cybed_license", "framework_summary")) {
    path <- file.path(conformance_dir, "goldens", paste0(name, ".csv"))
    raw <- readBin(path, "raw", file.size(path))
    expect_false(any(raw == as.raw(0x0d)), info = paste(name, "carries a CR byte"))

    text <- readLines(path, warn = FALSE)
    expect_false(
      any(grepl("(^|,)NA($|,)", text)),
      info = paste(name, "carries a literal NA field")
    )
  }
})
